import './styles.css';

export const metadata = {
  title: 'x | media record',
  description: 'Generated by create-nx-workspace',
};

export default function RecordLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return { children };
}
